FROM openjdk:8-jre-slim
ADD target/LoginAppTest-0.0.1-SNAPSHOT.jar /usr/share/
ENTRYPOINT ["/usr/"]
CMD ["sudo","chmod","+x","LoginAppTest-0.0.1-SNAPSHOT.jar"]
CMD [""java","-jar","LoginAppTest-0.0.1-SNAPSHOT.jar""]